# Generated by Django 2.1.7 on 2019-04-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfindex', '0002_auto_20190402_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='embed_url',
            field=models.CharField(max_length=1000),
        ),
    ]
